### ISSUE TITLE
KPZ101 Example Error

### ISSUE THREAD

**Issue by JoeyYin-SEU** [Thorlabs/Motion_Control_Examples#50]
The type use 81 at "TLI_GetDeviceListByTypeExt(serialNos, 100, 81);"
But 81 is the type of TPZ001. The right code is 21.

**Comment by JoeyYin-SEU** [comment]
What's more, we found a very ridiculous problem. When I use debug mode, the device cannot be found. But it will be normal at Release mode.Why?

**Comment by TrumanMetz** [comment]
Hello Joey, 
Thank you for bringing that typo to our attention and we will get that fixed. As for the debug and release issue, it seems like the new release of the KPC101 has caused some issues with the KPZ101 dlls which I believe might be causing this issue. We will be looking into this with the developers and working on a fix as soon as we can. If you contact your local tech support team (techsupport-cn@thorlabs.com) we can notify you of when the fix is available.
